openapi: 3.0.3
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
servers:
  - url: http://localhost:3001/api/v1
paths:
  /user/login:
    post:
    
      tags:
        - User Module
      summary: Login
      description: API for Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: Login Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Signup Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfile'
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/bankAccount:
    get:
      tags:
        - User Bank Account
      summary: Retrieve all bank accounts of the user
      description: Obtain all bank accounts associated with the authenticated user.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully retrieved all user bank accounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BankAccount'
        '400':
          description: Bad request, possibly due to invalid input parameters
        '401':
          description: Unauthorized, missing or invalid authentication
        '500':
          description: Internal server error
  /user/{accountId}:
    get:
      tags:
        - User Bank Account
      summary: Retrieve a specific user bank account
      description: Retrieve the details of a specific bank account belonging to the authenticated user.
      security:
        - BearerAuth: []
      parameters:
        - name: accountId
          in: path
          description: Id of the account
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully retrieved the details of the specified bank account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountIdResponse'
        '400':
          description: Bad request, possibly due to invalid input parameters
        '401':
          description: Unauthorized, missing or invalid authentication
        '500':
          description: Internal server error
  /user/bankAccount/{transactionId}:
    get:
      tags:
        - User Bank Account
      summary: Retrieve Details of a Specific User Transaction
      description: Fetch the details of a specific transaction associated with the user's bank account.
      security:
        - BearerAuth: []
      parameters:
        - name: transactionId
          in: path
          description: ID of the selected transaction
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successfully retrieved the details of the specified transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Bad request, possibly due to invalid input parameters
        '401':
          description: Unauthorized, missing or invalid authentication
        '500':
          description: Internal server error
    put:
      tags:
        - User Bank Account
      summary: Update a Specific User Transaction
      description: Update the details of a specific transaction associated with the user's bank account.
      security:
        - BearerAuth: []
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to update
          required: true
          schema:
             type: integer
             format: int64
      requestBody:
        description: The new details of the transaction to update.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequestBody'
      responses:
        '200':
          description: Successfully updated the transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
        '400':
          description: Bad request, possibly due to invalid input parameters
        '401':
          description: Unauthorized, missing or invalid authentication
        '500':
          description: Internal server error
    delete:
      tags:
        - User Bank Account
      summary: Delete a Specific User Transaction
      description: Delete a specific transaction associated with the user's bank account.
      security:
        - BearerAuth: []
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Successfully deleted the transaction
        '400':
          description: Bad request, possibly due to invalid input parameters
        '401':
          description: Unauthorized, missing or invalid authentication
        '500':
          description: Internal server error
components:
  securitySchemes:
    BearerAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          description: user email
        password:
          type: string
          description: user password
        firstName:
          type: string
          description: user first name
        lastName:
          type: string
          description: user last name
        userName:
          type: string
          description: user public name
    Login:
      type: object
      properties:
        email:
          type: string
          description: user email
        password:
          type: string
          description: user password
    ApiResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          properties:
            id:
              type: string
            email:
              type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    UserProfile:
      type: object
      properties:
        userName:
          type: string
    BankAccount:
      type: object
      properties:
        id:
          type: string
          description: Account ID
        accountName:
          type: string
          description: Account Name
        amount:
          type: number
          description: Account amount
        balance:
          type: string
          description: Balance
    AccountIdResponse:
      type: object
      properties:
        id:
          type: string
          description: Account ID
        accountName:
          type: string
          description: Account Name
        month:
          type: string
          format: date-time
          description: current month
        transactionId:
          type: integer
          description: transaction of the account
        amount:
          type: number
          description: Account amount
        balance:
          type: string
          description: Balance
    TransactionResponse:
      type: object
      properties:
        details:
          type: string
          description: Note for the Transaction
        category:
          type: string
          description: Category of the Transaction
    TransactionRequestBody:
      type: object
      properties:
        details:
          type: string
          description: Note for the Transaction
        category :
          type : string
          description : category for the transaction
